---
title: "proj data"
format: pdf
editor: visual
---

```{r}
####https://www.kaggle.com/datasets/ikynahidwin/depression-student-dataset
### 502 rows
### 11 columns

library(tidyverse)
library(ggplot2)
```

```{r}
depression <- read.csv("Depression Student Dataset.csv")
```

You can add options to executable code like this

```{r}
depression_age <- depression %>% group_by(Gender, Age, Depression) %>% summarise(count=n())

are_d <- depression_age %>% filter(Depression == "Yes")
are_nd <- depression_age %>% filter(Depression == "No")

ggplot(are_d, aes(x = Age, y = count, fill = Gender)) +
  geom_bar(stat = "identity", position = "dodge") + 
  labs(
    title = "Age of Depressed Students",
    x = "Age",
    y = "Total",
    fill = "Gender"
  ) +
  theme_minimal()+
  facet_wrap(~ Gender)

ggplot(are_nd, aes(x = Age, y = count, fill = Gender)) +
  geom_bar(stat = "identity", position = "dodge") + 
  labs(
    title = "Age of Not Depressed Students",
    x = "Age",
    y = "Total",
    fill = "Gender"
  ) +
  theme_minimal()+
  facet_wrap(~ Gender)

```
```{r}
depression_press <- depression %>% group_by(Gender, Academic.Pressure, Depression) %>% summarise(count=n())

ggplot(depression_press, aes(x = Academic.Pressure, y = count, fill = Gender)) +
  geom_bar(stat = "identity", position = "dodge") + 
  labs(
    title = "Academic Pressure of Students and Whether or not they are Depressed",
    x = "Academic Pressure",
    y = "Total",
    fill = "Gender"
  ) +
  theme_minimal()+
  facet_wrap(~ Depression)
```
```{r}
depression_study <- depression %>% group_by(Gender, Study.Satisfaction, Depression) %>% summarise(count=n())

ggplot(depression_study, aes(x = Study.Satisfaction, y = count, fill = Gender)) +
  geom_bar(stat = "identity", position = "dodge") + 
  labs(
    title = "Study Satisfaction of Students and Whether or not they are Depressed",
    x = "Academic Pressure (1-5)",
    y = "Total",
    fill = "Gender"
  ) +
  theme_minimal()+
  facet_wrap(~ Depression)
```
```{r}
depression_sleep <- depression %>% group_by(Gender, Sleep.Duration, Depression) %>% summarise(count=n())

#shortens categorical data so it's better read on the graph
depression_sleep <- depression_sleep %>%
  mutate(Sleep.Duration = recode(Sleep.Duration, "5-6 hours" = "5-6", "7-8 hours" = "7-8", "More than 8 hours" = "8<", "Less than 5 hours" = "<5"))

ggplot(depression_sleep, aes(x = Sleep.Duration, y = count, fill = Gender)) +
  geom_bar(stat = "identity", position = "dodge") + 
  labs(
    title = "How Long Students Sleep and Whether or not they are Depressed",
    x = "Hours Slept",
    y = "Total",
    fill = "Gender"
  ) +
  theme_minimal()+
  facet_wrap(~ Depression)


```
```{r}
depression_diet <- depression %>% group_by(Gender, Dietary.Habits, Depression) %>% summarise(count=n())

ggplot(depression_diet, aes(x = Dietary.Habits, y = count, fill = Gender)) +
  geom_bar(stat = "identity", position = "dodge") + 
  labs(
    title = "Diet of Students and Whether or not they are Depressed",
    x = "Diet",
    y = "Total",
    fill = "Gender"
  ) +
  theme_minimal()+
  facet_wrap(~ Depression)
```
```{r}
depression_suicidal <- depression %>% group_by(Gender, Have.you.ever.had.suicidal.thoughts.., Depression) %>% summarise(count=n())

ggplot(depression_suicidal, aes(x = Have.you.ever.had.suicidal.thoughts.., y = count, fill = Gender)) +
  geom_bar(stat = "identity", position = "dodge") + 
  labs(
    title = "Does the Student have Suicidal Thoughts? and Whether or not they are Depressed.",
    x = "Suicidal Thoughts?",
    y = "Total",
    fill = "Gender"
  ) +
  theme_minimal()+
  facet_wrap(~ Depression)
```
```{r}
depression_study_h <- depression %>% group_by(Gender, Study.Hours, Depression) %>% summarise(count=n())

ggplot(depression_study_h, aes(x = Study.Hours, y = count, fill = Gender)) +
  geom_bar(stat = "identity", position = "dodge") + 
  labs(
    title = "Study Hours of Students and Whether or not they are Depressed",
    x = "Study Hours",
    y = "Total",
    fill = "Gender"
  ) +
  theme_minimal()+
  facet_wrap(~ Depression)
```
```{r}
depression_finance <- depression %>% group_by(Gender, Financial.Stress, Depression) %>% summarise(count=n())

ggplot(depression_finance, aes(x = Financial.Stress, y = count, fill = Gender)) +
  geom_bar(stat = "identity", position = "dodge") + 
  labs(
    title = "Financial Stress of Students and Whether or not they are Depressed",
    x = "Finantial Stress (1-5)",
    y = "Total",
    fill = "Gender"
  ) +
  theme_minimal()+
  facet_wrap(~ Depression)
```
```{r}
depression_fam <- depression %>% group_by(Gender, Family.History.of.Mental.Illness, Depression) %>% summarise(count=n())

ggplot(depression_fam, aes(x = Family.History.of.Mental.Illness, y = count, fill = Gender)) +
  geom_bar(stat = "identity", position = "dodge") + 
  labs(
    title = "Does a Students have a Family History of Mental Illness? and Whether or not they are Depressed",
    x = "History of Illness",
    y = "Total",
    fill = "Gender"
  ) +
  theme_minimal()+
  facet_wrap(~ Depression)
```
```{r}
depression_is_depressed <- depression %>% group_by(Gender, Depression) %>% summarise(count = n())
depression_is_depressed

ggplot(depression_is_depressed, aes(x = Depression, y = count, fill = Gender)) + 
  geom_bar(stat = "Identity", position = "dodge") + labs(title = "Student Gender by Whether or not they are Depressed",
       x = "Are you Depressed?",
       y = "Count") +
  theme_minimal()

```

The `echo: false` option disables the printing of code (only output is displayed).
